### ISSUE TITLE
meteor add aldeed:tabular is not work with "Error,You must install tabular to use this package"

### ISSUE THREAD

**Issue by dzhdgi3dp** [scorpiusjs/scorpius#40]
I install scorpius with some error, can't fix.My meteor version is 1.4.2.3.

W20161213-17:05:04.585(8)? (STDERR) 
W20161213-17:05:04.586(8)? (STDERR) /home/goya/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161213-17:05:04.586(8)? (STDERR) 						throw(ex);
W20161213-17:05:04.586(8)? (STDERR) 						^
W20161213-17:05:04.607(8)? (STDERR) Error: You must install tabular to use this package [scorpius]
W20161213-17:05:04.608(8)? (STDERR)     at meteorInstall.node_modules.meteor.scorpiusjs:accounts.tabular.js (packages/scorpiusjs:accounts/tabular.js:12:9)
W20161213-17:05:04.608(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20161213-17:05:04.608(8)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20161213-17:05:04.608(8)? (STDERR)     at /home/goya/web/.meteor/local/build/programs/server/packages/scorpiusjs_accounts.js:1108:1
W20161213-17:05:04.608(8)? (STDERR)     at /home/goya/web/.meteor/local/build/programs/server/packages/scorpiusjs_accounts.js:1130:3
W20161213-17:05:04.608(8)? (STDERR)     at /home/goya/web/.meteor/local/build/programs/server/boot.js:295:34
W20161213-17:05:04.608(8)? (STDERR)     at Array.forEach (native)
W20161213-17:05:04.609(8)? (STDERR)     at Function._.each._.forEach (/home/goya/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20161213-17:05:04.609(8)? (STDERR)     at /home/goya/web/.meteor/local/build/programs/server/boot.js:128:5
W20161213-17:05:04.609(8)? (STDERR)     at /home/goya/web/.meteor/local/build/programs/server/boot.js:344:5

**Comment by deepupathak** [comment]
I face the same issue.

**Comment by dzhdgi3dp** [comment]
Console shows these messages :
I20161220-11:33:03.689(8)? Ignoring duplicate publish named 'tabular_genericPub'
I20161220-11:33:03.727(8)? Ignoring duplicate publish named 'tabular_getInfo'

**Comment by romans127** [comment]
Hello @dzhdgi3dp , 
Thank you for submitting this issue.
By  any chance is this a brand new setup, or is this upgrading for an existing project.

**Comment by dzhdgi3dp** [comment]
@rwatts3, errors occured in both new setup and existing project.

**Comment by gauravkeerthi** [comment]
+1

**Comment by romans127** [comment]
I've just published an update.
Please update and test.

**Comment by gauravkeerthi** [comment]
Works for me. Thanks! 
Unrelated question (sorry): since there is no official documentation for scorpius yet, can I just assume that I can refer to the OrionJs doc to learn how to use this (but change Orion to Scorpius each time)?

**Comment by romans127** [comment]
Certainly,

The 0 based releases of Scorpius was purely meant to help fix some of the outstanding bugs of Orion, and keep support for those who already created projects using Orion. Version 1.0 of Scorpius aims to be a complete rewrite using Vue.js as the view layer of the admin panel, and essentially turning Scorpius into a headless CMS. which would allow you to use any framework you'd like.

**Comment by chompomonim** [comment]
> Version 1.0 of Scorpius aims to be a complete rewrite using Vue.js as the view layer of the admin panel, and essentially turning Scorpius into a headless CMS. which would allow you to use any framework you'd like.

@rwatts3 are you already working on it or that's just ideas?

**Comment by romans127** [comment]
In very early stages of planning right now.
Researching Apollo, and Graphql for API layer.

**Comment by dzhdgi3dp** [comment]
After upgraded scorpiusjs:accounts to 0.3.1_2,installed "aldeed:tabular" "nicolaslopezj:tabular-materialize",still has same error. New project also has same error. @rwatts3  

>**Your app is crashing. Here's the latest log:**
>Ignoring duplicate publish named 'tabular_genericPub'
>Ignoring duplicate publish named 'tabular_getInfo'

>/home/goya/.meteor/packages/meteor->tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt->os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^
>Error: You must install tabular to use this package [scorpius]

**Comment by krishaamer** [comment]
Also getting this error now after update.

**Comment by romans127** [comment]
Ok this has been really difficult to debug, as some projects I was not able to replicate the problem at all, 
then in others including a new setup. I was able to reproduce the issue.

Please update and let me know if the new release to accounts fixes the issue.

**Comment by dzhdgi3dp** [comment]
accounts 0.3.1_3 is still same error. @rwatts3

**Comment by romans127** [comment]
weird, ok can you paste your packages file here .

**Comment by dzhdgi3dp** [comment]
accounts-base                      1.2.14  A user account system
accounts-password                  1.3.3  Password support for accounts
accounts-ui                        1.1.9  Simple templates to add login widge...
aldeed:tabular                     2.1.1  Datatables for large or small datas...
blaze-html-templates               1.0.5  Compile HTML templates into reactiv...
ecmascript                         0.6.1  Compiler plugin that supports ES201...
es5-shim                           4.6.15  Shims and polyfills to improve ECM...
insecure                           1.0.7  (For prototyping only) Allow all da...
jquery                             1.11.10  Manipulate the DOM using CSS sele...
kadira:blaze-layout                2.3.0  Layout Manager for Blaze (works wel...
kadira:flow-router                 2.12.1  Carefully Designed Client Side Rou...
less                               2.7.8  Leaner CSS language
meteor-base                        1.0.4  Packages that every Meteor app needs
mobile-experience                  1.0.4  Packages for a great mobile user ex...
mongo                              1.1.14  Adaptor for using MongoDB and Mini...
nicolaslopezj:tabular-materialize  1.4.1_4  Datatables for large or small dat...
reactive-var                       1.0.11  Reactive variable
scorpiusjs:accounts                0.3.1_3  Scorpius accounts manager
scorpiusjs:core                    0.3.1  A framework that makes complex as w...
shell-server                       0.2.1  Server-side component of the `meteo...
standard-minifier-css              1.3.2  Standard css minifier used with Met...
standard-minifier-js               1.2.1  Standard javascript minifiers used ...
tracker                            1.1.1  Dependency tracker to allow reactiv...
twbs:bootstrap                     3.3.6  The most popular front-end framewor...
useraccounts:bootstrap             1.14.2  Accounts Templates styled for Twit...

**Comment by romans127** [comment]
ok try removing nicolaslopezj:tabular-materialize and aldeed:tabular
my previous instruction may have been wrong.

**Comment by dzhdgi3dp** [comment]
Still can't work...

 >aldeed:tabular                     removed from your project
nicolaslopezj:tabular-materialize  removed from your project

>W20161222-10:17:25.161(8)? (STDERR)           
W20161222-10:17:25.190(8)? (STDERR) /home/goya/.meteor/packages/meteor-tool/.1.4.2_3.17tso1e++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20161222-10:17:25.191(8)? (STDERR) 						throw(ex);
W20161222-10:17:25.191(8)? (STDERR) 						^
W20161222-10:17:25.192(8)? (STDERR) Error: You must install tabular to use this package [scorpius]

**Comment by krishaamer** [comment]
I can confirm the error with an existing app (below) as well as a fresh clean install `meteor add scorpiusjs:core`.

```
adamkaczmarzyk:marker-animate-unobtrusive  0.0.17  Marker animation for Google Maps Javascript API v3
blaze-html-templates                       1.0.5  Compile HTML templates into reactive UI with Meteor Blaze
cosio55:autoform-cloudinary                0.0.2  Use Cloudinary with autoform/simpleschema to upload an image, and s...
d3js:d3                                    3.5.8  D3 (official): A JavaScript visualization library for HTML and SVG.
dburles:google-maps                        1.1.5  Google Maps Javascript API v3
easy:search                                2.1.5  Easy-to-use search with Blaze Components (+ Elastic Search Support)
ecmascript                                 0.6.1  Compiler plugin that supports ES2015+ in all .js files
erasaur:meteor-lodash                      4.0.0  Wrapper for Lo-Dash v4.0.0
es5-shim                                   4.6.15  Shims and polyfills to improve ECMAScript 5 support
flowkey:hotkeys                            1.2.0  Easy and effective hotkeys for your app, powered by Mousetrap
francocatena:status                        1.5.3  Displays the connection status between browser and server
jquery                                     1.11.10  Manipulate the DOM using CSS selectors
juliancwirko:postcss                       1.2.0  Minifier for Meteor with PostCSS processing - use Autoprefixer and ...
kadira:blaze-layout                        2.3.0  Layout Manager for Blaze (works well with FlowRouter)
kadira:flow-router                         2.12.1  Carefully Designed Client Side Router for Meteor
less                                       2.7.8  Leaner CSS language
lookback:body-class                        0.4.1  Automatically add classes for router templates and layouts for scop...
lukemadera:social-share                    1.2.0  Cross platform (inc. Cordova) social sharing for facebook, twitter,...
meteor-base                                1.0.4  Packages that every Meteor app needs
mobile-experience                          1.0.4  Packages for a great mobile user experience
mongo                                      1.1.14  Adaptor for using MongoDB and Minimongo over DDP
npm-bcrypt                                 0.9.2  Wrapper around the bcrypt npm package
okgrow:analytics                           2.0.1  Complete Google Analytics, Mixpanel, KISSmetrics (and more) integra...
okgrow:router-autoscroll                   0.1.8  Smart management of scroll position across route changes for Iron a...
ostrio:spiderable-middleware               1.0.2  Allow your JavaScript website to be crawled perfectly by search eng...
philippspo:momentum-flow-router            0.0.8  A momentum plugin for transitioning Flow Router pages
redhead:autoform-markdown-materialize      1.0.0_1  A simple autoform markdown with preview using perak:markdown and ...
scorpiusjs:core                            0.3.1  A framework that makes complex as well as simple apps possible with...
semantic:ui                                2.2.6_5  Official Semantic UI Integration for Meteor
session                                    1.1.7  Session variable
shell-server                               0.2.1  Server-side component of the `meteor shell` command.
smaltcreation:imagesloaded                 4.1.0  imagesloaded 4.1.0
standard-minifier-js                       1.2.1  Standard javascript minifiers used with Meteor apps by default.
tap:i18n                                   1.8.2  A comprehensive internationalization solution for Meteor
tap:i18n-ui                                0.8.0  User interface for the tap-i18n package
tracker                                    1.1.1  Dependency tracker to allow reactive callbacks
useraccounts:flow-routing                  1.14.2  UserAccounts package providing routes configuration capability via...
```

**Comment by romans127** [comment]
ok what Meteor version are you guys using. 
it's extremely hit or miss for some reason. 
it may be related to the apiVersion i set the packages to `1.4.2.3`

**Comment by krishaamer** [comment]
Meteor 1.4.2.3

**Comment by romans127** [comment]
Ok if you could pull the Scorpios repo and add the accounts package and see
if you can narrow down the potential cause. It appears the issue is either
going to be in the package.js dependencies or within tabular.js in the
meantime ill keep looking into the problems problem

**Comment by romans127** [comment]
I've tested this again with the latest releases and cannot confirm this error.
If anyone else is still having this issue please feel free to re-open.

**Comment by mmazloum** [comment]
Got it as well on a simple project with meteor 1.4.2.3

I'm using this package list : 
accounts-base@1.2.14
accounts-password@1.3.3
aldeed:autoform@5.8.1
aldeed:collection2@2.10.0
aldeed:collection2-core@1.2.0
aldeed:schema-deny@1.1.0
aldeed:schema-index@1.1.1
aldeed:simple-schema@1.5.3
aldeed:tabular@2.1.1
allow-deny@1.0.5
anti:i18n@0.4.3
autoupdate@1.3.12
babel-compiler@6.13.0
babel-runtime@1.0.1
base64@1.0.10
binary-heap@1.0.10
blaze@2.2.1
blaze-html-templates@1.0.5
blaze-tools@1.0.10
boilerplate-generator@1.0.11
caching-compiler@1.1.9
caching-html-compiler@1.0.7
callback-hook@1.0.10
check@1.2.4
coffeescript@1.11.1_4
dburles:collection-helpers@1.1.0
ddp@1.2.5
ddp-client@1.3.2
ddp-common@1.2.8
ddp-rate-limiter@1.0.6
ddp-server@1.3.12
deps@1.0.12
diff-sequence@1.0.7
ecmascript@0.6.1
ecmascript-runtime@0.3.15
ejson@1.0.13
email@1.1.18
es5-shim@4.6.15
fastclick@1.0.13
fortawesome:fontawesome@4.7.0
geojson-utils@1.0.10
hot-code-push@1.0.4
html-tools@1.0.11
htmljs@1.0.11
http@1.2.10
id-map@1.0.9
jeremy:selectize@0.12.1_5
jquery@1.11.10
kadira:blaze-layout@2.3.0
kadira:flow-router@2.12.1
launch-screen@1.1.0
less@2.7.8
livedata@1.0.18
localstorage@1.0.12
logging@1.1.16
matb33:collection-hooks@0.8.4
mdg:validation-error@0.5.1
meteor@1.6.0
meteor-base@1.0.4
meteor-platform@1.2.6
meteorhacks:inject-initial@1.0.4
minifier-css@1.2.15
minifier-js@1.2.15
minimongo@1.0.19
mobile-experience@1.0.4
mobile-status-bar@1.0.13
modules@0.7.7
modules-runtime@0.7.8
momentjs:moment@2.17.1
mongo@1.1.14
mongo-id@1.0.6
nicolaslopezj:options@1.0.1
nicolaslopezj:reactive-templates@1.2.1
nicolaslopezj:roles@2.6.3
nicolaslopezj:router-layer@0.0.11
npm-bcrypt@0.9.2
npm-mongo@2.2.11_2
observe-sequence@1.0.14
ordered-dict@1.0.9
promise@0.8.8
raix:eventemitter@0.1.3
random@1.0.10
rate-limit@1.0.6
reactive-dict@1.1.8
reactive-var@1.0.11
reload@1.1.11
retry@1.0.9
routepolicy@1.0.12
scorpiusjs:accounts@0.3.1_3
scorpiusjs:attributes@0.3.1
scorpiusjs:base@0.3.1_2
scorpiusjs:bootstrap@0.3.1
scorpiusjs:collections@0.3.1
scorpiusjs:config@0.3.1
scorpiusjs:core@0.3.1
scorpiusjs:dictionary@0.3.1
scorpiusjs:file-collection@0.3.1
scorpiusjs:filesystem@0.3.1
scorpiusjs:image-attribute@0.3.1
scorpiusjs:lang-en@0.3.1
scorpiusjs:relationships@0.3.1
scorpiusjs:summernote@0.3.1
service-configuration@1.0.11
session@1.1.7
sha@1.0.9
shell-server@0.2.1
softwarerero:accounts-t9n@1.3.7
spacebars@1.0.13
spacebars-compiler@1.0.13
srp@1.0.10
standard-minifier-css@1.3.2
standard-minifier-js@1.2.1
standard-minifiers@1.0.6
summernote:standalone@0.8.1
templating@1.2.15
templating-compiler@1.2.15
templating-runtime@1.2.15
templating-tools@1.0.5
tracker@1.1.1
twbs:bootstrap@3.3.6
ui@1.0.12
underscore@1.0.10
url@1.0.11
useraccounts:bootstrap@1.14.2
useraccounts:core@1.14.2
vsivsi:file-collection@1.3.7
webapp@1.3.12
webapp-hashing@1.0.9

with those meteor packages : 

meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.14                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.11            # Reactive variable for tracker
jquery@1.11.10                  # Helpful client-side library
tracker@1.1.1                 # Meteor's client-side reactive programming library

standard-minifier-css@1.3.2   # CSS minifier run for production mode
standard-minifier-js@1.2.1    # JS minifier run for production mode
es5-shim@4.6.15                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.6.1              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.1            # Server-side component of the `meteor shell` command

twbs:bootstrap
fortawesome:fontawesome
scorpiusjs:bootstrap
kadira:flow-router
kadira:blaze-layout
scorpiusjs:summernote
session@1.1.7
scorpiusjs:image-attribute
scorpiusjs:file-collection
scorpiusjs:filesystem
scorpiusjs:relationships
matb33:collection-hooks
aldeed:tabular

@rwatts3 i can share a repo with you if you wish

**Comment by mmazloum** [comment]
If I get back to meteor 1.4.1.1 and remove unecessary node modules everything goes fine.

**Comment by mostlyharmless2024** [comment]
I've only had the same problems with 1.4.2.x none of my projects will update to it without seeing similar "Error you must install x package" - I've mostly seen in mention "underscore" but also some others. I've tried full reinstall of meteor both on windows and linux, wiping it clean. My only success was with a  project after moving to a fresh install of Ubuntu.

Are you on Windows? I'm skeptical of the Windows meteor installation anymore...

**Comment by romans127** [comment]
I've too noticed this issue. I'm almost partial to say that it could be a bug in the meteor build process. Have you tried blitzing the meteor root and running a fresh install ? It thought it was particular to the tabular and accounts package, but after making several updates. I found that it was a race condition, where sometimes the error would show and other times it wouldn't . 

Try blitzing meteor, and reinstalling it using the curl command. 

```sh
curl https://install.meteor.com  | sh
```

In the meantime, i have noticed several issues as such, where working on a project sometimes on windows, then working on the same project in another os such as mac these type of problems arise.

The next release of Scorpius I will include a dockerfile and docker-compose.yml file to help create a consistent environment between different development hosts. If you are on board with this approach please give a thumbs up. if not thumbs down.

**Comment by romans127** [comment]
@mmazloum yes please share the repo, i'll try to reproduce

**Comment by ahmadsholehin** [comment]
@rwatts3 I managed to reproduce the error easily via the following. Using Meteor 1.4.2.3.

```
meteor create Test --bare
cd Test
meteor npm install
meteor add iron:router scorpiusjs:accounts
meteor npm install --save babel-runtime
meteor
```

**Comment by romans127** [comment]
@ahmadsholehin thank you for sharing this. I'm wondering at this point due to the frequency and randomness of this bug if it could be related to the build release of 1.4.2.3. 

I will be testing this further once the next version of meteor is released.

**Comment by romans127** [comment]
Please test the latest patch release for accounts.  Share results here.

**Comment by romans127** [comment]
No reports of issue remaining.  Therefore I'm going to close.  Reopen if it comes back.

**Comment by langtieshan** [comment]
The last version do not work on meteor 1.5
package have install success, I can visit  IP:3000/admin/my-account, 
but  have not view anything in window.
-----------------------------------------
#iron:router
kadira:flow-router 
kadira:blaze-layout
## scorpius
scorpiusjs:core
scorpiusjs:accounts
scorpiusjs:base
scorpiusjs:lang-en
scorpiusjs:collections
scorpiusjs:dictionary
scorpiusjs:attributes
scorpiusjs:config
## Styles  
twbs:bootstrap 
fortawesome:fontawesome 
#scorpiusjs:bootstrap will add  aldeed:tabular,that is error?????
#scorpiusjs:bootstrap
## Files
scorpiusjs:filesystem
scorpiusjs:file-collection 
scorpiusjs:file-attribute
scorpiusjs:image-attribute
_________________________
I will try it ......

**Comment by romans127** [comment]
Which Package are you referring to ?

**Comment by langtieshan** [comment]
scorpius is very good project.Thank you! 
but have some quesstion in the  latest version.

Meter verion is 1.5
Local package version is up-to-date: scorpiusjs:accounts@0.3.1_4
Local package version is up-to-date: scorpiusjs:attributes@0.3.1
Local package version is up-to-date: scorpiusjs:base@0.3.1_2
Local package version is up-to-date: scorpiusjs:collections@0.3.1
Local package version is up-to-date: scorpiusjs:config@0.3.1
Local package version is up-to-date: scorpiusjs:core@0.3.1
Local package version is up-to-date: scorpiusjs:dictionary@0.3.1
Local package version is up-to-date: scorpiusjs:file-attribute@0.3.1
Local package version is up-to-date: scorpiusjs:file-collection@0.3.1
Local package version is up-to-date: scorpiusjs:filesystem@0.3.1
Local package version is up-to-date: scorpiusjs:image-attribute@0.3.1
Local package version is up-to-date: scorpiusjs:lang-en@0.3.1
Local package version is up-to-date: scorpiusjs:summernote@0.3.1

**If you add package(scorpiusjs:bootstrap)and router(iron or kadira) package at the same time.
then below thing will occur,when you run your app. your client app will do not work.**
SERVER SIDE:
	I20170619-08:17:33.963(8)? Ignoring duplicate publish named 'tabular_genericPub'
	I20170619-08:17:33.964(8)? Ignoring duplicate publish named 'tabular_getInfo'
____________

CLIENT SIDE: (navigator)
templating-runtime.js?hash=c18de19…:55 Uncaught Error: There are multiple templates named 'tabular'. Each template needs a unique name.
    at Function.Template.__checkName (templating-runtime.js?hash=c18de19…:55)
    at template.tabular.js (aldeed_tabular.js?hash=bb7c31e…:896)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at tabular.html (aldeed_tabular.js?hash=bb7c31e…:883)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
    at main.js (main.js:1)
    at fileEvaluate (modules-runtime.js?hash=8587d18…:343)
    at require (modules-runtime.js?hash=8587d18…:238)
____________

So I mask package #scorpiusjs:bootstrap.

Below message is in my Console view,client app can work, but see nothing :( 
$ meteor --verbose
[[[[[ ~/app/testscorpius01 ]]]]]              

=> Started proxy.                             
Local package version is up-to-date: accounts-base@1.3.0
Local package version is up-to-date: accounts-password@1.3.7
Local package version is up-to-date: aldeed:autoform@5.8.1
Local package version is up-to-date: aldeed:collection2@2.10.0
Local package version is up-to-date: aldeed:collection2-core@1.2.0
Local package version is up-to-date: aldeed:schema-deny@1.1.0
Local package version is up-to-date: aldeed:schema-index@1.1.1
Local package version is up-to-date: aldeed:simple-schema@1.5.3
Local package version is up-to-date: allow-deny@1.0.5
Local package version is up-to-date: anti:i18n@0.4.3
Local package version is up-to-date: autoupdate@1.3.12
Local package version is up-to-date: babel-compiler@6.19.2
Local package version is up-to-date: babel-runtime@1.0.1
Local package version is up-to-date: base64@1.0.10
Local package version is up-to-date: binary-heap@1.0.10
Local package version is up-to-date: blaze@2.3.2
Local package version is up-to-date: blaze-html-templates@1.1.2
Local package version is up-to-date: blaze-tools@1.0.10
Local package version is up-to-date: boilerplate-generator@1.1.0
Local package version is up-to-date: caching-compiler@1.1.9
Local package version is up-to-date: caching-html-compiler@1.1.2
Local package version is up-to-date: callback-hook@1.0.10
Local package version is up-to-date: check@1.2.5
Local package version is up-to-date: coffeescript@1.12.3_1
Local package version is up-to-date: dburles:collection-helpers@1.1.0
Local package version is up-to-date: ddp@1.2.5
Local package version is up-to-date: ddp-client@1.3.4
Local package version is up-to-date: ddp-common@1.2.8
Local package version is up-to-date: ddp-rate-limiter@1.0.7
Local package version is up-to-date: ddp-server@1.3.14
Local package version is up-to-date: deps@1.0.12
Local package version is up-to-date: diff-sequence@1.0.7
Local package version is up-to-date: dynamic-import@0.1.1
Local package version is up-to-date: ecmascript@0.8.0
Local package version is up-to-date: ecmascript-runtime@0.4.1
Local package version is up-to-date: ecmascript-runtime-client@0.4.2
Local package version is up-to-date: ecmascript-runtime-server@0.4.1
Local package version is up-to-date: ejson@1.0.13
Local package version is up-to-date: email@1.2.3
Local package version is up-to-date: es5-shim@4.6.15
Local package version is up-to-date: fastclick@1.0.13
Local package version is up-to-date: fortawesome:fontawesome@4.7.0
Local package version is up-to-date: geojson-utils@1.0.10
Local package version is up-to-date: hot-code-push@1.0.4
Local package version is up-to-date: html-tools@1.0.11
Local package version is up-to-date: htmljs@1.0.11
Local package version is up-to-date: http@1.2.12
Local package version is up-to-date: id-map@1.0.9
Local package version is up-to-date: jquery@1.11.10
Local package version is up-to-date: kadira:blaze-layout@2.3.0
Local package version is up-to-date: kadira:flow-router@2.12.1
Local package version is up-to-date: launch-screen@1.1.1
Local package version is up-to-date: less@2.7.9
Local package version is up-to-date: livedata@1.0.18
Local package version is up-to-date: localstorage@1.1.0
Local package version is up-to-date: logging@1.1.17
Local package version is up-to-date: matb33:collection-hooks@0.8.4
Local package version is up-to-date: mdg:validation-error@0.5.1
Local package version is up-to-date: meteor@1.6.1
Local package version is up-to-date: meteor-base@1.1.0
Local package version is up-to-date: meteor-platform@1.2.6
Local package version is up-to-date: meteorhacks:inject-initial@1.0.4
Local package version is up-to-date: minifier-css@1.2.16
Local package version is up-to-date: minifier-js@2.1.0
Local package version is up-to-date: minimongo@1.2.1
Local package version is up-to-date: mobile-experience@1.0.4
Local package version is up-to-date: mobile-status-bar@1.0.14
Local package version is up-to-date: modules@0.9.1
Local package version is up-to-date: modules-runtime@0.8.0
Local package version is up-to-date: momentjs:moment@2.18.1
Local package version is up-to-date: mongo@1.1.18
Local package version is up-to-date: mongo-id@1.0.6
Local package version is up-to-date: nicolaslopezj:options@1.0.1
Local package version is up-to-date: nicolaslopezj:reactive-templates@1.2.1
Local package version is up-to-date: nicolaslopezj:roles@2.6.4
Local package version is up-to-date: nicolaslopezj:router-layer@0.0.11
Local package version is up-to-date: nicolaslopezj:tabular-materialize@1.4.1_4
Local package version is up-to-date: npm-bcrypt@0.9.3
Local package version is up-to-date: npm-mongo@2.2.24
Local package version is up-to-date: observe-sequence@1.0.16
Local package version is up-to-date: ordered-dict@1.0.9
Local package version is up-to-date: promise@0.8.9
Local package version is up-to-date: raix:eventemitter@0.1.3
Local package version is up-to-date: random@1.0.10
Local package version is up-to-date: rate-limit@1.0.8
Local package version is up-to-date: reactive-dict@1.1.9
Local package version is up-to-date: reactive-var@1.0.11
Local package version is up-to-date: reload@1.1.11
Local package version is up-to-date: retry@1.0.9
Local package version is up-to-date: routepolicy@1.0.12
**Local package version is up-to-date: scorpiusjs:accounts@0.3.1_4
Local package version is up-to-date: scorpiusjs:attributes@0.3.1
Local package version is up-to-date: scorpiusjs:base@0.3.1_2
Local package version is up-to-date: scorpiusjs:collections@0.3.1
Local package version is up-to-date: scorpiusjs:config@0.3.1
Local package version is up-to-date: scorpiusjs:core@0.3.1
Local package version is up-to-date: scorpiusjs:dictionary@0.3.1
Local package version is up-to-date: scorpiusjs:file-attribute@0.3.1
Local package version is up-to-date: scorpiusjs:file-collection@0.3.1
Local package version is up-to-date: scorpiusjs:filesystem@0.3.1
Local package version is up-to-date: scorpiusjs:image-attribute@0.3.1
Local package version is up-to-date: scorpiusjs:lang-en@0.3.1
Local package version is up-to-date: scorpiusjs:summernote@0.3.1**
Local package version is up-to-date: service-configuration@1.0.11
Local package version is up-to-date: session@1.1.7
Local package version is up-to-date: sha@1.0.9
Local package version is up-to-date: shell-server@0.2.3
Local package version is up-to-date: softwarerero:accounts-t9n@1.3.9
Local package version is up-to-date: spacebars@1.0.15
Local package version is up-to-date: spacebars-compiler@1.1.2
Local package version is up-to-date: srp@1.0.10
Local package version is up-to-date: standard-minifier-css@1.3.4
Local package version is up-to-date: standard-minifier-js@2.1.0
Local package version is up-to-date: standard-minifiers@1.1.0
Local package version is up-to-date: summernote:standalone@0.8.1
Local package version is up-to-date: templating@1.3.2
Local package version is up-to-date: templating-compiler@1.3.2
Local package version is up-to-date: templating-runtime@1.3.2
Local package version is up-to-date: templating-tools@1.1.2
Local package version is up-to-date: tracker@1.1.3
Local package version is up-to-date: twbs:bootstrap@3.3.6
Local package version is up-to-date: ui@1.0.13
Local package version is up-to-date: underscore@1.0.10
Local package version is up-to-date: url@1.1.0
Local package version is up-to-date: useraccounts:core@1.14.2
Local package version is up-to-date: vsivsi:file-collection@1.3.8
Local package version is up-to-date: webapp@1.3.16
Local package version is up-to-date: webapp-hashing@1.0.9

**Comment by romans127** [comment]
The next version of Scorpius will be tested against 1.5. Currently the latest supported version of Meteor is `1.4.2.3`. Once testing is complete, and packages are updated to newer versions. A new version of Scorpius will be released. As for a timeline I am pushing for within the next week. I'll leave this issue open for testing once Scorpius is upgraded to the next version.

**Comment by langtieshan** [comment]
Great job!
Thank you!
Good lucky!
